Add test CI action
natasha-codes/snek pull request #3
Opened 2019-11-06 04:47 UTC by nathanshelly

2019-11-06 04:55 UTC, sashaweiss commented
no tests pls add tests

2019-11-06 04:57 UTC, sashaweiss requested changes

2019-11-06 04:57 UTC, sashaweiss commented on .github/workflows/build_and_test.yml
> +      run: cargo test --verbose
there are no tests pls add tests

2019-11-06 05:02 UTC, nathanshelly commented on .github/workflows/build_and_test.yml
> +      run: cargo test --verbose
tests added

2019-11-06 05:05 UTC, sashaweiss requested changes

2019-11-06 05:05 UTC, sashaweiss commented on src/snek/foo.rs
> +    panic!();
test is failing pls make test not fail

2019-11-10 02:49 UTC, sashaweiss approved these changes
lgtm

2019-11-10 02:49 UTC, sashaweiss commented
prefer this as a squash merge, if that's kosher

2019-11-10 06:19 UTC, merged